In [16]:
%run "../0 - Base/inicializa.ipynb"

-------------

# Cadastro

In [17]:
DF_Cadastro = pd.read_csv("..\\Raw\\RAW_CADASTRO_PRODUTOS.csv")

In [18]:
DF_Cadastro.shape

(23, 5)

In [19]:
DF_Cadastro.columns

Index(['COD_PROD', 'CATEGORIA_BRUTA', 'NOME_PRODUTO', 'VALOR_VENDA_CADASTRO',
       'CUSTO_CADASTRO'],
      dtype='str')

In [20]:
DF_Cadastro.head(5)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VALOR_VENDA_CADASTRO,CUSTO_CADASTRO
0,101,HORTIFRUTI,Tomate Debora kg,"7,90",3.2
1,102,Horti Fruti,BANANA PRATA KG,5.5,"2,10"
2,103,Hortifruti,Alface Americana un,3.5,1.2
3,104,HORTI,Batata Monalisa kg,5.9,2.5
4,105,Hortifruti,Cebola Nacional kg,NaN,2.8

-----

# Perdas

In [21]:
DF_Perdas = pd.read_csv("..\\Raw\\RAW_CADERNO_PERDAS.csv")

In [22]:
DF_Perdas.head(5)

,DATA_OCORRENCIA,SETOR_ORIGEM,DESCRICAO_MOTIVO_TEXTO_LIVRE,COD_PROD_OU_NOME,QTD_AVARIADA,VALOR_ESTIMADO_PREJUIZO,REGISTRADO_POR
0,01/01/2026,DEPOSITO,Falta de mercadoria no estoque - suspeita furto,601,1.10,"R$ 14,18",Diego
1,03/01/2026,HORTI,podre descartado no lixo,601,6.92,"R$ 100,71",Betao
2,04/01/2026,Açougue,Lata amassada no descarregamento,DIFERENCA CAIXA,7.95,"R$ 98,53",Betao
3,06/01/2026,CARNES,Diferenca de peso na balanca,501,1.07,"R$ 19,3",DESCONHECIDO
4,07/01/2026,HORTI,Sobra de pao dormido,PAO,4.59,"R$ 158,44",Diego

In [23]:
DF_Perdas.shape

(46, 7)

In [24]:
DF_Perdas.columns

Index(['DATA_OCORRENCIA', 'SETOR_ORIGEM', 'DESCRICAO_MOTIVO_TEXTO_LIVRE',
       'COD_PROD_OU_NOME', 'QTD_AVARIADA', 'VALOR_ESTIMADO_PREJUIZO',
       'REGISTRADO_POR'],
      dtype='str')

-----

# Compras

In [25]:
DF_Compras = pd.read_csv("..\\Raw\\RAW_COMPRAS_ENTRADAS.csv")

In [26]:
DF_Compras.shape

(402, 7)

In [27]:
DF_Compras.columns

Index(['NUM_NOTA_FISCAL', 'DATA_ENTRADA', 'FORNECEDOR', 'COD_PROD',
       'QTD_COMPRADA', 'VALOR_TOTAL_NOTA', 'RESPONSAVEL_RECEBIMENTO'],
      dtype='str')

In [28]:
DF_Compras.head(5)

,NUM_NOTA_FISCAL,DATA_ENTRADA,FORNECEDOR,COD_PROD,QTD_COMPRADA,VALOR_TOTAL_NOTA,RESPONSAVEL_RECEBIMENTO
0,NF-1006,01/01/2026,CEASA SP - PRODUTORES UNIDOS,101,55,163.39,Mateus
1,NF-1046,01/01/2026,CEASA SP - PRODUTORES UNIDOS,102,119,335.78,Thiago
2,NF-1018,01/01/2026,CEASA SP - PRODUTORES UNIDOS,103,115 KG,243.92,Thiago
3,NF-1013,01/01/2026,CEASA SP - PRODUTORES UNIDOS,104,41,123.78,diego
4,NF-1004,01/01/2026,CEASA SP - PRODUTORES UNIDOS,105,85,235.48,Diego

------

# Vendas

In [29]:
DF_Vendas = pd.read_csv("..\\Raw\\RAW_VENDAS_POS.csv")

In [30]:
DF_Vendas.shape

(15822, 10)

In [31]:
DF_Vendas.columns

Index(['ID_TRANSACAO', 'DATA_HORA_VENDA', 'PDV_CAIXA', 'OPERADOR',
       'COD_PRODUTO', 'QTD_VENDIDA', 'PRECO_UNIT_COBRADO', 'TOTAL_PAGO',
       'FORMA_PAGTO', 'STATUS_VENDA'],
      dtype='str')

In [32]:
DF_Vendas.head(5)

,ID_TRANSACAO,DATA_HORA_VENDA,PDV_CAIXA,OPERADOR,COD_PRODUTO,QTD_VENDIDA,PRECO_UNIT_COBRADO,TOTAL_PAGO,FORMA_PAGTO,STATUS_VENDA
0,900001,2026-01-01,CAIXA_PRINCIPAL,Juliana,503.0,5.0,3.94,19.70,FIADO_CADERNETO,CONCLUIDA
1,900002,2026-01-01,caixa 02,Patricia,NaN,2.0,34.47,68.94,FIADO_CADERNETO,CONCLUIDA
2,900003,2026-01-01,caixa 02,Patricia,404.0,4.0,32.32,129.28,FIADO_CADERNETO,CONCLUIDA
3,900004,2026-01-01,caixa 02,Patricia,303.0,4.0,36.05,144.20,CARTAO_CREDITO,CONCLUIDA
4,900005,2026-01-01,CX_02,Patricia,304.0,5.0,25.25,126.25,Cartao Debito,CONCLUIDA

-----