In [1]:
%run "../0 - Base/inicializa.ipynb"

In [2]:
silverCadadastro = pd.read_excel("..\\Raw\\table_silver\\silverCadastro_ETL.xlsx")

-----

# MEDIDAS planilha Cadastro ETL

In [3]:
silverCadadastro.head(10)

,COD_PROD,CATEGORIA_BRUTA,NOME_PRODUTO,VENDA_CADASTRO,CUSTO_VENDA,MARGEM,PESO,UNIDADE
0,101,HORTIFRUTI,TOMATE DEBORA,7.90,3.20,4.70,1.00,KG
1,102,HORTIFRUTI,BANANA PRATA,5.50,2.10,3.40,1.00,KG
2,103,HORTIFRUTI,ALFACE AMERICANA,3.50,1.20,2.30,1.00,UN
3,104,HORTIFRUTI,BATATA MONALISA,5.90,2.50,3.40,1.00,KG
4,105,HORTIFRUTI,CEBOLA NACIONAL,0.00,2.80,-2.80,1.00,KG
5,201,ACOUGUE,PICANHA BOV RESFRIADA,79.90,42.00,37.90,1.00,KG
6,202,ACOUGUE,ALCATRA C/ MAMINHA,44.90,26.00,18.90,1.00,KG
7,203,ACOUGUE,CARNE MOIDA DE 2A,29.90,14.00,15.90,1.00,KG
8,204,ACOUGUE,LINGUICA TOSCANA,22.90,12.00,10.90,1.00,KG
9,301,FRIOS E LATICINIOS,QUEIJO MUSSARELA,42.90,26.00,16.90,1.00,PCA

In [4]:
silverCadadastro['COD_PROD'].value_counts()

COD_PROD
101        1
102        1
103        1
104        1
105        1
201        1
202        1
203        1
204        1
301        1
302        1
303        1
304        1
401        1
402        1
403        1
404        1
501        1
502        1
503        1
601        1
602        1
1000001    1
999        1
Name: count, dtype: int64

In [5]:
silverCadadastro.columns

Index(['COD_PROD', 'CATEGORIA_BRUTA', 'NOME_PRODUTO', 'VENDA_CADASTRO',
       'CUSTO_VENDA', 'MARGEM', 'PESO', 'UNIDADE'],
      dtype='str')

In [6]:
silverCadadastro.shape

(24, 8)

------

## Cria tabelas com dados agrupados

In [7]:
gold_Cadastro = silverCadadastro # criar uma nova tabela com dados importados

In [8]:
resumo = gold_Cadastro.groupby('CATEGORIA_BRUTA').agg(
      PRODUTOS=('COD_PROD', 'count'),
      PRECO_MEDIO=('VENDA_CADASTRO', 'mean'),
      CUSTO_MEDIO=('CUSTO_VENDA', 'mean'),
      MARGEM_MEDIA=('MARGEM', 'mean'),
)

In [9]:
# retirado por redundancia
# gold_s_venda = (
#     gold_Cadastro
#     .groupby('CATEGORIA_BRUTA', as_index=False)['VENDA_CADASTRO']
#     .sum()
# )

In [10]:
# # retirado por redundancia
# gold_s_custo = (
#     gold_Cadastro
#     .groupby('CATEGORIA_BRUTA', as_index=False)['CUSTO_VENDA']
#     .sum()
# )

In [11]:
# retirado por redundancia
# gold_s_margem = (
#     gold_Cadastro
#     .groupby('CATEGORIA_BRUTA', as_index=False)['MARGEM']
#     .sum()
# )

-----

In [12]:
resumo.head(5)

                    PRODUTOS  PRECO_MEDIO  CUSTO_MEDIO  MARGEM_MEDIA
CATEGORIA_BRUTA
ACOUGUE                    4        44.40        23.50         20.90
BEBIDAS                    3         6.09         3.37          2.73
FRIOS E LATICINIOS         4        19.27        12.15          7.12
HORTIFRUTI                 5         4.56         2.36          2.20
MERCEARIA                  1        16.90        11.50          5.40

## Cria vizualizacao com dados agrupados

In [13]:
## SOMA SEM SENTIDO

# #soma os dados categoria x margem
# silverCadadastro.groupby('CATEGORIA_BRUTA')['MARGEM'].sum()

------

In [14]:
resultado = False

In [15]:
def export_dados_excel(resultado):

    pasta = Path("..\\Raw\\table_gold\\")
    pasta.mkdir(parents=True, exist_ok=True)

    if resultado:

        arquivo_excel = pasta / "gold_Cadastro.xlsx"

        # 1. Criar os arquivos
        gold_Cadastro.to_excel(arquivo_excel, index=False)


        # 3. Consolidar em um Excel com duas abas
        with pd.ExcelWriter(arquivo_excel, engine="openpyxl") as writer:

            gold_Cadastro.to_excel(
                writer,
                sheet_name="g_cadastro",
                index=False
            )


            resumo.to_excel(
                writer,
                sheet_name="resumo",
                index=False
            )


        return True

    print("ERRO")
    return False

In [16]:
export_dados_excel(True)

True

------

In [17]:
### FIM